### ISSUE TITLE
Start Surfing button doesn't close the popup

### ISSUE THREAD

**Issue by JohnDotOwl** [emanuelepaiano/espresso-portal#1]
Hi,

After the users click on get 1 hour free , it shows a timer and a Start Surfing. How do i close that popup , clicking the Start surfing doesn't do anything(For iPad)

For iPhones it shows the popup to click on One Hour Free after only about 1-2 minutes .... very long delay, any idea why? , android does shows a popup, any idea?

**Comment by rainbowhat** [comment]
[Fri Jan 19 04:07:01.955651 2018] [:error] [pid 17712] [client 219.75.50.204:52156] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:01.955901 2018] [:error] [pid 17712] [client 219.75.50.204:52156] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:01.955972 2018] [:error] [pid 17712] [client 219.75.50.204:52156] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:02.516520 2018] [:error] [pid 17714] [client 219.75.50.204:52158] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:02.516673 2018] [:error] [pid 17714] [client 219.75.50.204:52158] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:03.487253 2018] [:error] [pid 17567] [client 219.75.50.204:52163] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:03.487422 2018] [:error] [pid 17567] [client 219.75.50.204:52163] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:03.487490 2018] [:error] [pid 17567] [client 219.75.50.204:52163] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:21.401778 2018] [:error] [pid 17711] [client 219.75.50.204:52164] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/guest/s/default/class.unifi.php:1328\nStack trace:\n#0 /var/www/html/guest/s/default/class.unifi.php(78): unifiapi->get_curl_obj()\n#1 /var/www/html/guest/s/default/core.inc.php(199): unifiapi->login()\n#2 /var/www/html/guest/s/default/authorized.php(84): authorizeGuest('5c:ad:cf:8b:c8:...', '90', '10240', '6400', '600')\n#3 {main}\n  thrown in /var/www/html/guest/s/default/class.unifi.php on line 1328, referer: http://172.104.173.249/guest/s/default/?id=5c:ad:cf:8b:c8:b6&ap=78:8a:20:83:f4:9c&t=1516334817&url=http://captive.apple.com%2fhotspot-detect.html&ssid=Guest+-+Testing+In+Progress
[Fri Jan 19 04:07:21.455078 2018] [:error] [pid 17564] [client 219.75.50.204:52166] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:21.455242 2018] [:error] [pid 17564] [client 219.75.50.204:52166] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:21.455307 2018] [:error] [pid 17564] [client 219.75.50.204:52166] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:21.577809 2018] [:error] [pid 17713] [client 219.75.50.204:52168] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:21.577949 2018] [:error] [pid 17713] [client 219.75.50.204:52168] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:21.578020 2018] [:error] [pid 17713] [client 219.75.50.204:52168] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42

**Comment by rainbowhat** [comment]
[Fri Jan 19 04:07:01.955651 2018] [:error] [pid 17712] [client 219.75.50.204:52156] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:01.955901 2018] [:error] [pid 17712] [client 219.75.50.204:52156] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:01.955972 2018] [:error] [pid 17712] [client 219.75.50.204:52156] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:02.516520 2018] [:error] [pid 17714] [client 219.75.50.204:52158] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:02.516673 2018] [:error] [pid 17714] [client 219.75.50.204:52158] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:03.487253 2018] [:error] [pid 17567] [client 219.75.50.204:52163] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:03.487422 2018] [:error] [pid 17567] [client 219.75.50.204:52163] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:03.487490 2018] [:error] [pid 17567] [client 219.75.50.204:52163] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:21.401778 2018] [:error] [pid 17711] [client 219.75.50.204:52164] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/guest/s/default/class.unifi.php:1328\nStack trace:\n#0 /var/www/html/guest/s/default/class.unifi.php(78): unifiapi->get_curl_obj()\n#1 /var/www/html/guest/s/default/core.inc.php(199): unifiapi->login()\n#2 /var/www/html/guest/s/default/authorized.php(84): authorizeGuest('5c:ad:cf:8b:c8:...', '90', '10240', '6400', '600')\n#3 {main}\n  thrown in /var/www/html/guest/s/default/class.unifi.php on line 1328, referer: http://123.104.123.249/guest/s/default/?id=5c:ad:cf:8b:c8:b6&ap=78:8a:20:13:f4:9c&t=1516334817&url=http://captive.apple.com%2fhotspot-detect.html&ssid=ABC+-+Testing+In+Progress
[Fri Jan 19 04:07:21.455078 2018] [:error] [pid 17564] [client 219.75.50.204:52166] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:21.455242 2018] [:error] [pid 17564] [client 219.75.50.204:52166] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:21.455307 2018] [:error] [pid 17564] [client 219.75.50.204:52166] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42
[Fri Jan 19 04:07:21.577809 2018] [:error] [pid 17713] [client 219.75.50.204:52168] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/guest/s/default/core.inc.php on line 58
[Fri Jan 19 04:07:21.577949 2018] [:error] [pid 17713] [client 219.75.50.204:52168] PHP Notice:  Undefined variable: id in /var/www/html/guest/s/default/html/content_en.html on line 41
[Fri Jan 19 04:07:21.578020 2018] [:error] [pid 17713] [client 219.75.50.204:52168] PHP Notice:  Undefined variable: ap in /var/www/html/guest/s/default/html/content_en.html on line 42

**Comment by emanuelepaiano** [comment]
Hi, sorry for late reply, but I saw now this message.... 

1) At moment I haven't an iPad, so i will debug when I found one.

2) I haven't any problem with iphones... my test works successfully...

Thank you for reporting.
